In [1]:
import numpy as np # import numpy

**Example 1**

In [2]:
arr1 = np.array([10,20,30,40,50])

In [3]:
arr2 = np.array([5,6,7,8,9])

In [4]:
arr1+arr2 # add

array([15, 26, 37, 48, 59])

In [9]:
arr3 = np.array([1,3,5,7,9]) # 5 element

In [10]:
arr4 = np.array([2,4,6,8]) # 4 element

In [11]:
arr3+arr4 # add 

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

**Example 2**

In [12]:
arr1 = np.array([10,20,30,40,50])

In [13]:
arr2 = np.array([5,6,7,8,9])

In [14]:
arr1-arr2

array([ 5, 14, 23, 32, 41])

**Example 3**

In [15]:
arr1 = np.array([5,6,7,8,9])

In [16]:
arr1+10 # per element add 10

array([15, 16, 17, 18, 19])

**Example 4**

In [17]:
arr1 = np.array([10,20,30,40,50])

In [18]:
arr2 = np.array([5,6,7,8,9])

In [19]:
arr1*arr2

array([ 50, 120, 210, 320, 450])

**Example 5**

In [20]:
arr1 = np.array([10,20,30,40,50])

In [21]:
arr1 ** 0.5

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [22]:
arr1 **2

array([ 100,  400,  900, 1600, 2500], dtype=int32)