In [1]:
import numpy as np # import numpy

**Example 1**

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[:3] = 100

In [5]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [6]:
arr[4:7] = [200,201,202]

In [7]:
arr

array([100, 100, 100,   4, 200, 201, 202,   8,   9])

**Example 2**

In [8]:
arr = np.arange(1,10)

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2 = arr

In [11]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2[:4] = 100

In [13]:
arr2

array([100, 100, 100, 100,   5,   6,   7,   8,   9])

In [14]:
arr # arr changing

array([100, 100, 100, 100,   5,   6,   7,   8,   9])

**Example 3**

In [17]:
array1 = np.arange(1,10)

In [18]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array2 = array1.copy()

In [20]:
array2[:3]=100

In [21]:
array2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [22]:
array1 # not change

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Example 4**

In [23]:
arr3 = np.arange(1,21)

In [24]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
arr3 = arr3.reshape(5,4)

In [26]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
arr3[:,:2] # get first 2 column of all rows

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [30]:
arr3[1,:2] # get first 2 column of 1. row

array([5, 6])

In [32]:
arr3[::2,:2] # get first 2 column and step 2 in rows

array([[ 1,  2],
       [ 9, 10],
       [17, 18]])

**Example 5**

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 3 # Filter

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
arr2 = [5,12,26,8,44,13,65]

In [37]:
npArr = np.array(arr2)

In [38]:
npArr

array([ 5, 12, 26,  8, 44, 13, 65])

In [39]:
npArr > 10 

array([False,  True,  True, False,  True,  True,  True])

In [40]:
npArr[npArr > 10]

array([12, 26, 44, 13, 65])