In [1]:
import numpy as np # import numpy module as np

**Example**

In [5]:
data_list = [1,2,3,4,5,6] # list

In [6]:
arr = np.array(data_list) # convert to numpy array

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

**Example 2**

In [8]:
data_list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
arr2 = np.array(data_list2)

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Access**

In [11]:
arr2[1][1]

5

In [12]:
# or

In [13]:
arr2[1,1]

5

**arange**

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,7)

array([3, 4, 5, 6])

**zeros**

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**ones**

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

**linspace**

In [21]:
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [23]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [24]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [25]:
np.linspace(0,99,10)

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [26]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

**eye**

In [27]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**random randint**

In [29]:
np.random.randint(0,10) # random one number 0-10

5

In [31]:
np.random.randint(0,10,5) # random 5 number 0-10

array([4, 7, 6, 3, 2])

**random rand**

In [34]:
np.random.rand(5)  # random 5 number 0-1 

array([0.32033619, 0.12871696, 0.64119487, 0.13342955, 0.58995868])

**random randn**

In [36]:
np.random.randn(5) # random 5 number around 0 (standard normal distribution)

array([-1.79240336, -1.33443303, -0.50807336, -1.9436515 ,  0.89335831])

**reshape**

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.reshape(5,5) # 5x5 matris

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max argmax**

In [44]:
newarr = np.random.randint(1,100,10)

In [45]:
newarr

array([74, 48, 36, 65, 54, 65, 71, 84, 20, 97])

In [46]:
newarr.max()  # max number

97

In [47]:
newarr.argmax() # max number index

9

**compute determinant**

In [48]:
detarr = np.random.randint(1,10,4)

In [49]:
detarr

array([1, 7, 5, 5])

In [50]:
detarr = detarr.reshape(2,2)

In [51]:
detarr

array([[1, 7],
       [5, 5]])

In [52]:
np.linalg.det(detarr)

-29.99999999999999